services:
  tests:
    image: node:24-alpine
    volumes:
      - ./tests:/opt/tests
    entrypoint: ["sh", "letsgo-tests.sh"]
    working_dir: '/opt/tests'
  spring:
    image: maven:3.6.3-openjdk-17-slim
    volumes:
      - ./es1:/opt/es1
      - ./es1/m2:/root/.m2
    command: ["sh", "letsgo-maven.sh"]
    working_dir: '/opt/es1'
    ports:
      - 8080:8080
